name = "CuTe"
uuid = "57a5148a-7bb8-46c0-adfc-97cbfb31d94c"
authors = ["MilkshakeForReal <yicheng.wu@ucalgary.ca> and contributors"]
version = "1.0.0-DEV"

[deps]

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test","SafeTestsets"]
