name = "CuTe"
uuid = "57a5148a-7bb8-46c0-adfc-97cbfb31d94c"
authors = ["MilkshakeForReal <yicheng.wu@ucalgary.ca> and contributors"]
version = "1.0.0"

[deps]
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[compat]
julia = "1.8"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"

[targets]
test = ["Test", "SafeTestsets", "Static"]
